#!/bin/bash

last_git_tag=$(git describe --tags --dirty=-d --abbrev=1 --first-parent)
last_git_tag=${last_git_tag:-$(git describe --all --dirty=-d --abbrev=1 --first-parent)}
docker push -t $docker_tag