#!/bin/bash
export release_name=bionic

# install tzdata avoiding interactive prompts
ln -fs /usr/share/zoneinfo/Europa/London /etc/localtime
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install gnupg2 tzdata -y
dpkg-reconfigure --frontend noninteractive tzdata

# add ros melodic repo
sh -c 'echo "deb http://packages.ros.org/ros/ubuntu ${release_name} main" > /etc/apt/sources.list.d/ros-latest.list'
apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# install the base environment and all build tools
apt-get update
apt-get install build-essential git python3-pip python-pip cmake ros-melodic-robot -y
pip --no-cache-dir install -U rosdep rosinstall_generator vcstool rosinstall em catkin-tools

# complete the ros installation
rosdep init
rosdep update

# prepare the workspace folder
mkdir -p /ros_catkin_ws/src

# cleanup
apt-get clean autoclean -y
